[target.thumbv7m-none-eabi]
runner = "arm-none-eabi-gdb -q -x bluepill.gdb"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
rustflags = [ "-Clink-arg=-Tlink.x" ]

[build]
target = "thumbv7m-none-eabi"
