[target.thumbv7m-none-eabi]
runner = "arm-none-eabi-gdb -q -x dbg/stm32f103.gdb"

[target.thumbv7em-none-eabihf]
runner = "arm-none-eabi-gdb -q -x dbg/stm32f401.gdb"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
rustflags = [ "-Clink-arg=-Tlink.x" ]
